application:
  domain: pentest-hub
  name: 'PENTEST HUB'
  customMetricsPrefix: pentesthub
  welcomeBanner:
    showOnFirstStart: false
  chatBot:
    name: 'Anonymous'
challenges:
  xssBonusPayload: '<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/321927177&color=%23ff5500&auto_play=true&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>'
hackingInstructor:
  avatarImage: juicyEvilWasp.png
